// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ogidi/church-media/ent/attendancerecord"
	"github.com/ogidi/church-media/ent/predicate"
)

// AttendanceRecordDelete is the builder for deleting a AttendanceRecord entity.
type AttendanceRecordDelete struct {
	config
	hooks    []Hook
	mutation *AttendanceRecordMutation
}

// Where appends a list predicates to the AttendanceRecordDelete builder.
func (ard *AttendanceRecordDelete) Where(ps ...predicate.AttendanceRecord) *AttendanceRecordDelete {
	ard.mutation.Where(ps...)
	return ard
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ard *AttendanceRecordDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, ard.sqlExec, ard.mutation, ard.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (ard *AttendanceRecordDelete) ExecX(ctx context.Context) int {
	n, err := ard.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ard *AttendanceRecordDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(attendancerecord.Table, sqlgraph.NewFieldSpec(attendancerecord.FieldID, field.TypeInt))
	if ps := ard.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ard.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	ard.mutation.done = true
	return affected, err
}

// AttendanceRecordDeleteOne is the builder for deleting a single AttendanceRecord entity.
type AttendanceRecordDeleteOne struct {
	ard *AttendanceRecordDelete
}

// Where appends a list predicates to the AttendanceRecordDelete builder.
func (ardo *AttendanceRecordDeleteOne) Where(ps ...predicate.AttendanceRecord) *AttendanceRecordDeleteOne {
	ardo.ard.mutation.Where(ps...)
	return ardo
}

// Exec executes the deletion query.
func (ardo *AttendanceRecordDeleteOne) Exec(ctx context.Context) error {
	n, err := ardo.ard.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{attendancerecord.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ardo *AttendanceRecordDeleteOne) ExecX(ctx context.Context) {
	if err := ardo.Exec(ctx); err != nil {
		panic(err)
	}
}
