// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ogidi/church-media/ent/contactprofile"
	"github.com/ogidi/church-media/ent/predicate"
	"github.com/ogidi/church-media/ent/user"
)

// ContactProfileQuery is the builder for querying ContactProfile entities.
type ContactProfileQuery struct {
	config
	ctx        *QueryContext
	order      []contactprofile.OrderOption
	inters     []Interceptor
	predicates []predicate.ContactProfile
	withUser   *UserQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ContactProfileQuery builder.
func (cpq *ContactProfileQuery) Where(ps ...predicate.ContactProfile) *ContactProfileQuery {
	cpq.predicates = append(cpq.predicates, ps...)
	return cpq
}

// Limit the number of records to be returned by this query.
func (cpq *ContactProfileQuery) Limit(limit int) *ContactProfileQuery {
	cpq.ctx.Limit = &limit
	return cpq
}

// Offset to start from.
func (cpq *ContactProfileQuery) Offset(offset int) *ContactProfileQuery {
	cpq.ctx.Offset = &offset
	return cpq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cpq *ContactProfileQuery) Unique(unique bool) *ContactProfileQuery {
	cpq.ctx.Unique = &unique
	return cpq
}

// Order specifies how the records should be ordered.
func (cpq *ContactProfileQuery) Order(o ...contactprofile.OrderOption) *ContactProfileQuery {
	cpq.order = append(cpq.order, o...)
	return cpq
}

// QueryUser chains the current query on the "user" edge.
func (cpq *ContactProfileQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: cpq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := cpq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := cpq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(contactprofile.Table, contactprofile.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, contactprofile.UserTable, contactprofile.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(cpq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first ContactProfile entity from the query.
// Returns a *NotFoundError when no ContactProfile was found.
func (cpq *ContactProfileQuery) First(ctx context.Context) (*ContactProfile, error) {
	nodes, err := cpq.Limit(1).All(setContextOp(ctx, cpq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{contactprofile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cpq *ContactProfileQuery) FirstX(ctx context.Context) *ContactProfile {
	node, err := cpq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ContactProfile ID from the query.
// Returns a *NotFoundError when no ContactProfile ID was found.
func (cpq *ContactProfileQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cpq.Limit(1).IDs(setContextOp(ctx, cpq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{contactprofile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cpq *ContactProfileQuery) FirstIDX(ctx context.Context) int {
	id, err := cpq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ContactProfile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ContactProfile entity is found.
// Returns a *NotFoundError when no ContactProfile entities are found.
func (cpq *ContactProfileQuery) Only(ctx context.Context) (*ContactProfile, error) {
	nodes, err := cpq.Limit(2).All(setContextOp(ctx, cpq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{contactprofile.Label}
	default:
		return nil, &NotSingularError{contactprofile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cpq *ContactProfileQuery) OnlyX(ctx context.Context) *ContactProfile {
	node, err := cpq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ContactProfile ID in the query.
// Returns a *NotSingularError when more than one ContactProfile ID is found.
// Returns a *NotFoundError when no entities are found.
func (cpq *ContactProfileQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cpq.Limit(2).IDs(setContextOp(ctx, cpq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{contactprofile.Label}
	default:
		err = &NotSingularError{contactprofile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cpq *ContactProfileQuery) OnlyIDX(ctx context.Context) int {
	id, err := cpq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ContactProfiles.
func (cpq *ContactProfileQuery) All(ctx context.Context) ([]*ContactProfile, error) {
	ctx = setContextOp(ctx, cpq.ctx, ent.OpQueryAll)
	if err := cpq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ContactProfile, *ContactProfileQuery]()
	return withInterceptors[[]*ContactProfile](ctx, cpq, qr, cpq.inters)
}

// AllX is like All, but panics if an error occurs.
func (cpq *ContactProfileQuery) AllX(ctx context.Context) []*ContactProfile {
	nodes, err := cpq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ContactProfile IDs.
func (cpq *ContactProfileQuery) IDs(ctx context.Context) (ids []int, err error) {
	if cpq.ctx.Unique == nil && cpq.path != nil {
		cpq.Unique(true)
	}
	ctx = setContextOp(ctx, cpq.ctx, ent.OpQueryIDs)
	if err = cpq.Select(contactprofile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cpq *ContactProfileQuery) IDsX(ctx context.Context) []int {
	ids, err := cpq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cpq *ContactProfileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, cpq.ctx, ent.OpQueryCount)
	if err := cpq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, cpq, querierCount[*ContactProfileQuery](), cpq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (cpq *ContactProfileQuery) CountX(ctx context.Context) int {
	count, err := cpq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cpq *ContactProfileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, cpq.ctx, ent.OpQueryExist)
	switch _, err := cpq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (cpq *ContactProfileQuery) ExistX(ctx context.Context) bool {
	exist, err := cpq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ContactProfileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cpq *ContactProfileQuery) Clone() *ContactProfileQuery {
	if cpq == nil {
		return nil
	}
	return &ContactProfileQuery{
		config:     cpq.config,
		ctx:        cpq.ctx.Clone(),
		order:      append([]contactprofile.OrderOption{}, cpq.order...),
		inters:     append([]Interceptor{}, cpq.inters...),
		predicates: append([]predicate.ContactProfile{}, cpq.predicates...),
		withUser:   cpq.withUser.Clone(),
		// clone intermediate query.
		sql:  cpq.sql.Clone(),
		path: cpq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (cpq *ContactProfileQuery) WithUser(opts ...func(*UserQuery)) *ContactProfileQuery {
	query := (&UserClient{config: cpq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	cpq.withUser = query
	return cpq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		FirstName string `json:"first_name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ContactProfile.Query().
//		GroupBy(contactprofile.FieldFirstName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (cpq *ContactProfileQuery) GroupBy(field string, fields ...string) *ContactProfileGroupBy {
	cpq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ContactProfileGroupBy{build: cpq}
	grbuild.flds = &cpq.ctx.Fields
	grbuild.label = contactprofile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		FirstName string `json:"first_name,omitempty"`
//	}
//
//	client.ContactProfile.Query().
//		Select(contactprofile.FieldFirstName).
//		Scan(ctx, &v)
func (cpq *ContactProfileQuery) Select(fields ...string) *ContactProfileSelect {
	cpq.ctx.Fields = append(cpq.ctx.Fields, fields...)
	sbuild := &ContactProfileSelect{ContactProfileQuery: cpq}
	sbuild.label = contactprofile.Label
	sbuild.flds, sbuild.scan = &cpq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ContactProfileSelect configured with the given aggregations.
func (cpq *ContactProfileQuery) Aggregate(fns ...AggregateFunc) *ContactProfileSelect {
	return cpq.Select().Aggregate(fns...)
}

func (cpq *ContactProfileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range cpq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, cpq); err != nil {
				return err
			}
		}
	}
	for _, f := range cpq.ctx.Fields {
		if !contactprofile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cpq.path != nil {
		prev, err := cpq.path(ctx)
		if err != nil {
			return err
		}
		cpq.sql = prev
	}
	return nil
}

func (cpq *ContactProfileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ContactProfile, error) {
	var (
		nodes       = []*ContactProfile{}
		withFKs     = cpq.withFKs
		_spec       = cpq.querySpec()
		loadedTypes = [1]bool{
			cpq.withUser != nil,
		}
	)
	if cpq.withUser != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, contactprofile.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ContactProfile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ContactProfile{config: cpq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, cpq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := cpq.withUser; query != nil {
		if err := cpq.loadUser(ctx, query, nodes, nil,
			func(n *ContactProfile, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (cpq *ContactProfileQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*ContactProfile, init func(*ContactProfile), assign func(*ContactProfile, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*ContactProfile)
	for i := range nodes {
		if nodes[i].user_contact_profile == nil {
			continue
		}
		fk := *nodes[i].user_contact_profile
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_contact_profile" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (cpq *ContactProfileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cpq.querySpec()
	_spec.Node.Columns = cpq.ctx.Fields
	if len(cpq.ctx.Fields) > 0 {
		_spec.Unique = cpq.ctx.Unique != nil && *cpq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, cpq.driver, _spec)
}

func (cpq *ContactProfileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(contactprofile.Table, contactprofile.Columns, sqlgraph.NewFieldSpec(contactprofile.FieldID, field.TypeInt))
	_spec.From = cpq.sql
	if unique := cpq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if cpq.path != nil {
		_spec.Unique = true
	}
	if fields := cpq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, contactprofile.FieldID)
		for i := range fields {
			if fields[i] != contactprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cpq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cpq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cpq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cpq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cpq *ContactProfileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cpq.driver.Dialect())
	t1 := builder.Table(contactprofile.Table)
	columns := cpq.ctx.Fields
	if len(columns) == 0 {
		columns = contactprofile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cpq.sql != nil {
		selector = cpq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cpq.ctx.Unique != nil && *cpq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range cpq.predicates {
		p(selector)
	}
	for _, p := range cpq.order {
		p(selector)
	}
	if offset := cpq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cpq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ContactProfileGroupBy is the group-by builder for ContactProfile entities.
type ContactProfileGroupBy struct {
	selector
	build *ContactProfileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cpgb *ContactProfileGroupBy) Aggregate(fns ...AggregateFunc) *ContactProfileGroupBy {
	cpgb.fns = append(cpgb.fns, fns...)
	return cpgb
}

// Scan applies the selector query and scans the result into the given value.
func (cpgb *ContactProfileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cpgb.build.ctx, ent.OpQueryGroupBy)
	if err := cpgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContactProfileQuery, *ContactProfileGroupBy](ctx, cpgb.build, cpgb, cpgb.build.inters, v)
}

func (cpgb *ContactProfileGroupBy) sqlScan(ctx context.Context, root *ContactProfileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(cpgb.fns))
	for _, fn := range cpgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*cpgb.flds)+len(cpgb.fns))
		for _, f := range *cpgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*cpgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cpgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ContactProfileSelect is the builder for selecting fields of ContactProfile entities.
type ContactProfileSelect struct {
	*ContactProfileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cps *ContactProfileSelect) Aggregate(fns ...AggregateFunc) *ContactProfileSelect {
	cps.fns = append(cps.fns, fns...)
	return cps
}

// Scan applies the selector query and scans the result into the given value.
func (cps *ContactProfileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cps.ctx, ent.OpQuerySelect)
	if err := cps.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ContactProfileQuery, *ContactProfileSelect](ctx, cps.ContactProfileQuery, cps, cps.inters, v)
}

func (cps *ContactProfileSelect) sqlScan(ctx context.Context, root *ContactProfileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cps.fns))
	for _, fn := range cps.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cps.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cps.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
