// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ogidi/church-media/ent/logaudit"
	"github.com/ogidi/church-media/ent/predicate"
)

// LogAuditDelete is the builder for deleting a LogAudit entity.
type LogAuditDelete struct {
	config
	hooks    []Hook
	mutation *LogAuditMutation
}

// Where appends a list predicates to the LogAuditDelete builder.
func (lad *LogAuditDelete) Where(ps ...predicate.LogAudit) *LogAuditDelete {
	lad.mutation.Where(ps...)
	return lad
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (lad *LogAuditDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, lad.sqlExec, lad.mutation, lad.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (lad *LogAuditDelete) ExecX(ctx context.Context) int {
	n, err := lad.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (lad *LogAuditDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(logaudit.Table, sqlgraph.NewFieldSpec(logaudit.FieldID, field.TypeInt))
	if ps := lad.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, lad.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	lad.mutation.done = true
	return affected, err
}

// LogAuditDeleteOne is the builder for deleting a single LogAudit entity.
type LogAuditDeleteOne struct {
	lad *LogAuditDelete
}

// Where appends a list predicates to the LogAuditDelete builder.
func (lado *LogAuditDeleteOne) Where(ps ...predicate.LogAudit) *LogAuditDeleteOne {
	lado.lad.mutation.Where(ps...)
	return lado
}

// Exec executes the deletion query.
func (lado *LogAuditDeleteOne) Exec(ctx context.Context) error {
	n, err := lado.lad.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{logaudit.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (lado *LogAuditDeleteOne) ExecX(ctx context.Context) {
	if err := lado.Exec(ctx); err != nil {
		panic(err)
	}
}
