// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ogidi/church-media/ent/message"
	"github.com/ogidi/church-media/ent/predicate"
	"github.com/ogidi/church-media/ent/response"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetName sets the "name" field.
func (mu *MessageUpdate) SetName(s string) *MessageUpdate {
	mu.mutation.SetName(s)
	return mu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableName(s *string) *MessageUpdate {
	if s != nil {
		mu.SetName(*s)
	}
	return mu
}

// SetEmail sets the "email" field.
func (mu *MessageUpdate) SetEmail(s string) *MessageUpdate {
	mu.mutation.SetEmail(s)
	return mu
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableEmail(s *string) *MessageUpdate {
	if s != nil {
		mu.SetEmail(*s)
	}
	return mu
}

// SetPhone sets the "phone" field.
func (mu *MessageUpdate) SetPhone(s string) *MessageUpdate {
	mu.mutation.SetPhone(s)
	return mu
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (mu *MessageUpdate) SetNillablePhone(s *string) *MessageUpdate {
	if s != nil {
		mu.SetPhone(*s)
	}
	return mu
}

// ClearPhone clears the value of the "phone" field.
func (mu *MessageUpdate) ClearPhone() *MessageUpdate {
	mu.mutation.ClearPhone()
	return mu
}

// SetSubject sets the "subject" field.
func (mu *MessageUpdate) SetSubject(m message.Subject) *MessageUpdate {
	mu.mutation.SetSubject(m)
	return mu
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableSubject(m *message.Subject) *MessageUpdate {
	if m != nil {
		mu.SetSubject(*m)
	}
	return mu
}

// SetState sets the "state" field.
func (mu *MessageUpdate) SetState(m message.State) *MessageUpdate {
	mu.mutation.SetState(m)
	return mu
}

// SetNillableState sets the "state" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableState(m *message.State) *MessageUpdate {
	if m != nil {
		mu.SetState(*m)
	}
	return mu
}

// SetDescription sets the "description" field.
func (mu *MessageUpdate) SetDescription(s string) *MessageUpdate {
	mu.mutation.SetDescription(s)
	return mu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableDescription(s *string) *MessageUpdate {
	if s != nil {
		mu.SetDescription(*s)
	}
	return mu
}

// SetCreatedAt sets the "created_at" field.
func (mu *MessageUpdate) SetCreatedAt(t time.Time) *MessageUpdate {
	mu.mutation.SetCreatedAt(t)
	return mu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableCreatedAt(t *time.Time) *MessageUpdate {
	if t != nil {
		mu.SetCreatedAt(*t)
	}
	return mu
}

// AddResponseIDs adds the "responses" edge to the Response entity by IDs.
func (mu *MessageUpdate) AddResponseIDs(ids ...int) *MessageUpdate {
	mu.mutation.AddResponseIDs(ids...)
	return mu
}

// AddResponses adds the "responses" edges to the Response entity.
func (mu *MessageUpdate) AddResponses(r ...*Response) *MessageUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return mu.AddResponseIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearResponses clears all "responses" edges to the Response entity.
func (mu *MessageUpdate) ClearResponses() *MessageUpdate {
	mu.mutation.ClearResponses()
	return mu
}

// RemoveResponseIDs removes the "responses" edge to Response entities by IDs.
func (mu *MessageUpdate) RemoveResponseIDs(ids ...int) *MessageUpdate {
	mu.mutation.RemoveResponseIDs(ids...)
	return mu
}

// RemoveResponses removes "responses" edges to Response entities.
func (mu *MessageUpdate) RemoveResponses(r ...*Response) *MessageUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return mu.RemoveResponseIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if v, ok := mu.mutation.Subject(); ok {
		if err := message.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Message.subject": %w`, err)}
		}
	}
	if v, ok := mu.mutation.State(); ok {
		if err := message.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Message.state": %w`, err)}
		}
	}
	return nil
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Name(); ok {
		_spec.SetField(message.FieldName, field.TypeString, value)
	}
	if value, ok := mu.mutation.Email(); ok {
		_spec.SetField(message.FieldEmail, field.TypeString, value)
	}
	if value, ok := mu.mutation.Phone(); ok {
		_spec.SetField(message.FieldPhone, field.TypeString, value)
	}
	if mu.mutation.PhoneCleared() {
		_spec.ClearField(message.FieldPhone, field.TypeString)
	}
	if value, ok := mu.mutation.Subject(); ok {
		_spec.SetField(message.FieldSubject, field.TypeEnum, value)
	}
	if value, ok := mu.mutation.State(); ok {
		_spec.SetField(message.FieldState, field.TypeEnum, value)
	}
	if value, ok := mu.mutation.Description(); ok {
		_spec.SetField(message.FieldDescription, field.TypeString, value)
	}
	if value, ok := mu.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if mu.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ResponsesTable,
			Columns: []string{message.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedResponsesIDs(); len(nodes) > 0 && !mu.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ResponsesTable,
			Columns: []string{message.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ResponsesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ResponsesTable,
			Columns: []string{message.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetName sets the "name" field.
func (muo *MessageUpdateOne) SetName(s string) *MessageUpdateOne {
	muo.mutation.SetName(s)
	return muo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableName(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetName(*s)
	}
	return muo
}

// SetEmail sets the "email" field.
func (muo *MessageUpdateOne) SetEmail(s string) *MessageUpdateOne {
	muo.mutation.SetEmail(s)
	return muo
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableEmail(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetEmail(*s)
	}
	return muo
}

// SetPhone sets the "phone" field.
func (muo *MessageUpdateOne) SetPhone(s string) *MessageUpdateOne {
	muo.mutation.SetPhone(s)
	return muo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillablePhone(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetPhone(*s)
	}
	return muo
}

// ClearPhone clears the value of the "phone" field.
func (muo *MessageUpdateOne) ClearPhone() *MessageUpdateOne {
	muo.mutation.ClearPhone()
	return muo
}

// SetSubject sets the "subject" field.
func (muo *MessageUpdateOne) SetSubject(m message.Subject) *MessageUpdateOne {
	muo.mutation.SetSubject(m)
	return muo
}

// SetNillableSubject sets the "subject" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableSubject(m *message.Subject) *MessageUpdateOne {
	if m != nil {
		muo.SetSubject(*m)
	}
	return muo
}

// SetState sets the "state" field.
func (muo *MessageUpdateOne) SetState(m message.State) *MessageUpdateOne {
	muo.mutation.SetState(m)
	return muo
}

// SetNillableState sets the "state" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableState(m *message.State) *MessageUpdateOne {
	if m != nil {
		muo.SetState(*m)
	}
	return muo
}

// SetDescription sets the "description" field.
func (muo *MessageUpdateOne) SetDescription(s string) *MessageUpdateOne {
	muo.mutation.SetDescription(s)
	return muo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableDescription(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetDescription(*s)
	}
	return muo
}

// SetCreatedAt sets the "created_at" field.
func (muo *MessageUpdateOne) SetCreatedAt(t time.Time) *MessageUpdateOne {
	muo.mutation.SetCreatedAt(t)
	return muo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableCreatedAt(t *time.Time) *MessageUpdateOne {
	if t != nil {
		muo.SetCreatedAt(*t)
	}
	return muo
}

// AddResponseIDs adds the "responses" edge to the Response entity by IDs.
func (muo *MessageUpdateOne) AddResponseIDs(ids ...int) *MessageUpdateOne {
	muo.mutation.AddResponseIDs(ids...)
	return muo
}

// AddResponses adds the "responses" edges to the Response entity.
func (muo *MessageUpdateOne) AddResponses(r ...*Response) *MessageUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return muo.AddResponseIDs(ids...)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearResponses clears all "responses" edges to the Response entity.
func (muo *MessageUpdateOne) ClearResponses() *MessageUpdateOne {
	muo.mutation.ClearResponses()
	return muo
}

// RemoveResponseIDs removes the "responses" edge to Response entities by IDs.
func (muo *MessageUpdateOne) RemoveResponseIDs(ids ...int) *MessageUpdateOne {
	muo.mutation.RemoveResponseIDs(ids...)
	return muo
}

// RemoveResponses removes "responses" edges to Response entities.
func (muo *MessageUpdateOne) RemoveResponses(r ...*Response) *MessageUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return muo.RemoveResponseIDs(ids...)
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if v, ok := muo.mutation.Subject(); ok {
		if err := message.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "Message.subject": %w`, err)}
		}
	}
	if v, ok := muo.mutation.State(); ok {
		if err := message.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Message.state": %w`, err)}
		}
	}
	return nil
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeInt))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Name(); ok {
		_spec.SetField(message.FieldName, field.TypeString, value)
	}
	if value, ok := muo.mutation.Email(); ok {
		_spec.SetField(message.FieldEmail, field.TypeString, value)
	}
	if value, ok := muo.mutation.Phone(); ok {
		_spec.SetField(message.FieldPhone, field.TypeString, value)
	}
	if muo.mutation.PhoneCleared() {
		_spec.ClearField(message.FieldPhone, field.TypeString)
	}
	if value, ok := muo.mutation.Subject(); ok {
		_spec.SetField(message.FieldSubject, field.TypeEnum, value)
	}
	if value, ok := muo.mutation.State(); ok {
		_spec.SetField(message.FieldState, field.TypeEnum, value)
	}
	if value, ok := muo.mutation.Description(); ok {
		_spec.SetField(message.FieldDescription, field.TypeString, value)
	}
	if value, ok := muo.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeTime, value)
	}
	if muo.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ResponsesTable,
			Columns: []string{message.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedResponsesIDs(); len(nodes) > 0 && !muo.mutation.ResponsesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ResponsesTable,
			Columns: []string{message.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ResponsesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   message.ResponsesTable,
			Columns: []string{message.ResponsesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(response.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
